# .pre-commit-config.yaml
repos:
# Astral Ruff pre-commit hooks.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

# Run unit tests.
- repo: local
  hooks:
    - id: pytest
      name: pytest-unit-tests
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      args: [tests/unit]